TasteBuddies/Models/Group.cs
using System.ComponentModel.DataAnnotations;

namespace TasteBuddies.Models
{
    public class Group
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Name is required.")]
        [StringLength(100, ErrorMessage = "Name cannot exceed 100 characters")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Description is required.")]
        [StringLength(1000, ErrorMessage = "Description cannot exceed 1000 characters")]
        public string Description { get; set; }

        public List<User>? Users { get; set; } = new List<User>();


        public Group()
        {

        }

        public Group(string name, string description)
        {
            Name = name;
            Description = description;

        }
    }
}

TasteBuddies/Controllers/GroupsController.cs
using Microsoft.AspNetCore.Mvc;
using TasteBuddies.DataAccess;
using TasteBuddies.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using System.Reflection.Metadata.Ecma335;
using System.Security.Cryptography;
using Serilog;
using Microsoft.Extensions.Hosting;

namespace TasteBuddies.Controllers
{
    public class GroupsController : Controller
    {
        private readonly TasteBuddiesContext _context;

        public GroupsController(TasteBuddiesContext context)
        {
            _context = context;
        }





        // This action returns a list of all groups.
        // If the user has a valid "CurrentUser" cookie, it retrieves the user from the database and sets it to the ViewBag.
        // If the user does not have a valid "CurrentUser" cookie, it redirects them to the Home controller's Index action.

        public IActionResult Index( bool groupCreated = false)
        {

            var groups = _context.Groups;

            string id = Request.Cookies["CurrentUser"].ToString();


            if (string.IsNullOrEmpty(id) || !int.TryParse(id, out int userId))
            {
                // Handle the case where the cookie is missing or invalid
                return RedirectToAction("Index", "Home"); // Redirect to Index page 
            }



            int parseId = Int32.Parse(id);

            var groupsWithUsers = _context.Groups.Include(g => g.Users);

            User user = new User();

            foreach (var group in groupsWithUsers)
            {

                foreach (var user1 in group.Users)
                {

                    if (user1.Id == parseId)
                    {
                        user = user1;
                        break;
                    }

                }
            }

            ViewBag.user = user;
            ViewBag.GroupCreated = groupCreated;

            return View(groups);
        }




        // This action returns the view for creating a new group.

        [Route("/Groups/New")]
        public IActionResult New()
        {
            return View();
        }




        // This action handles the creation of a new group.
        // It first checks for a valid "CurrentUser" cookie.
        // If the cookie is valid, it associates the current user with the group being created and then saves it.
        // It also logs the creation of the group.
        // After creation, it sets a "CurrentGroup" cookie and redirects the user back to the list of groups.

        [HttpPost]
        [Route("/Groups")]
        public IActionResult Create(Group group)
        {
            if (ModelState.IsValid)
            {

                string id = Request.Cookies["CurrentUser"].ToString();

                if (string.IsNullOrEmpty(id) || !int.TryParse(id, out int userId))
                {
                    // Handle the case where the cookie is missing or invalid
                    return RedirectToAction("Index", "Home"); // Redirect to login page 
                }


                int parseId = Int32.Parse(id);


                var dbUser = _context.Users.FirstOrDefault(u => u.Id == parseId);
                if (dbUser is null)
                {
                    return NotFound();
                }

                group.Users.Add(dbUser);


                _context.Add(group);
                _context.SaveChanges();
                Log.Information($"A new [{group.Id}]group has been created by [{id}]user.");

                Response.Cookies.Append("CurrentGroup", group.Id.ToString());

                return RedirectToPage("/Groups", new {  groupCreated = true });
            }
            else
            {
                Log.Warning("Group model is not valid");

                return View("New", group);
            }
        }


        // This action handles a user joining a group.
        // It first checks for a valid "CurrentUser" cookie.
        // If the cookie is valid, it associates the current user with the group they want to join and then saves the changes.
        // It also logs the action.
        // After joining, it redirects the user to their profile page.
        [HttpPost]
        public IActionResult Join()
        {

            string id = Request.Cookies["CurrentUser"].ToString();

            if (string.IsNullOrEmpty(id) || !int.TryParse(id, out int userId))
            {
                // Handle the case where the cookie is missing or invalid
                return RedirectToAction("Index", "Home"); // Redirect to login page 
            }


            int parseId = Int32.Parse(id);

            int groupId = Int32.Parse(Request.Form["GroupId"]);



            var dbUser = _context.Users.FirstOrDefault(u => u.Id == parseId);
            var dbGroup = _context.Groups.FirstOrDefault(g => g.Id == groupId);
            if (dbUser is null || dbGroup is null)
            {
                return NotFound();
            }

            dbGroup.Users.Add(dbUser);


            _context.SaveChanges();
            Log.Information($"A [{dbUser.Id}]user has joined a new [{dbGroup.Id}]group.");

            return RedirectToAction("Profile", "Users");
        }
    }
}

TasteBuddies/Views/Groups/Index.cshtml
@model IEnumerable<Group>


@if (ViewBag.GroupCreated)
{
    <script>
        window.onload = function () {
            alert('Your new Group has been created successfully.');
        }
    </script>
}


<div class="col-md-6 offset-lg-3 align-middle" style="margin-top: 25px">

    <h1 class="text-center">Active TasteBuddies Groups</h1>

    <h5 class="text-center">Have a special culinary interest? Connect with other users!</h5>


    @foreach (var group in Model)
    {
        <div class="group-container">

            <h2 class="group-info">@group.Name</h2>

            <p class="group-info">@group.Description</p>

            @if (ViewBag.user.Groups.Contains(group))
            {
                <p class="group-info">You are already in this group</p>
            }

            else
            {
                <form method="post" action="@Url.Action("Join", "Groups")">

                    <input class="form-control" type="hidden" name="GroupId" value="@group.Id" />

                    <button class="btn btn-success join-button" type="submit">Join</button>

                </form>
            }

        </div>
    }



    <h5 class="text-center">Don't see a group that fits your needs? Create one!</h5>

    <form method="get" action="/groups/new">

        <div class="d-grid gap-2">

            <button class="btn btn-success" id="CreateButton" type="submit">Create Group</button>

        </div>

    </form>

</div>

<style>

    .group-container {
        background-color: #f8f9fa;
        padding: 20px;
        border: 1px solid #dee2e6;
        margin-bottom: 20px;
        text-align: center;
    }

        .group-container h2 {
            font-size: 1.5rem;
        }


        .group-container p {
            font-size: 1rem;
        }


    .join-button {
        margin-top: 10px;
    }


    #CreateButton {
        margin-bottom: 50px;
    }


    .group-info {
        color: black
    }

</style>

TasteBuddies/Views/Groups/New.cshtml
@model Group

<div class="col-md-6 offset-lg-3 align-middle" style="margin-top: 25px">

    <h1 class=" justify-content-center">Create a TasteBuddies Group</h1>


    <form method="post" action="/Groups">


        <div class="form-group">

            <label class="form-label" for="Name">Name: </label>

            <input class="form-control" type="text" id="Name" name="Name" placeholder="Name" />

            <span asp-validation-for="Name" class="text-danger"></span>
        </div>


        <div class="form-group">

            <label class="form-label" for="Description">Description: </label>

            <input class="form-control" type="text" id="Description" name="Description" maxlength="500" placeholder="Description" />

            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        
        <br />


        <div class="d-grid gap-2">

            <button class="btn btn-success" type="submit">Create Group</button>

        </div>


    </form>


</div>